_wandb:
    value:
        cli_version: 0.23.1
        e:
            pjjo4ixgqmfjuftex9bsy69ituvln1zu:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "2147483648"
                codePath: benchmarl/abs_project/main2.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "183728447488"
                executable: /Users/andrea/miniconda3/envs/abs-project/bin/python
                git:
                    commit: 7e1e0eaa402551398d9aa3b1f3a65bea264365a5
                    remote: git@github.com:Itonkdong/abs-project.git
                host: Andreas-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: benchmarl/abs_project/main2.ipynb
                python: CPython 3.11.14
                root: /Users/andrea/Projects/abs/abs-project/benchmarl/abs_project/mappo_reverse_transport_mlp__832204fe_26_01_12-17_18_44
                startedAt: "2026-01-12T16:18:45.614784Z"
                writerId: pjjo4ixgqmfjuftex9bsy69ituvln1zu
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 41
                - 50
                - 105
            "3":
                - 2
                - 3
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
algorithm_config:
    value:
        clip_epsilon: 0.2
        critic_coef: 1
        entropy_coef: 0
        lmbda: 0.9
        loss_critic_type: l2
        minibatch_advantage: false
        scale_mapping: biased_softplus_1.0
        share_param_critic: true
        use_tanh_normal: true
algorithm_name:
    value: mappo
continuous_actions:
    value: true
critic_model_config:
    value:
        _is_critic: true
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 256
            - 256
        num_feature_dims: 1
critic_model_name:
    value: mlp
environment_name:
    value: vmas
experiment_config:
    value:
        adam_eps: 1e-06
        buffer_device: cpu
        checkpoint_at_end: false
        checkpoint_interval: 0
        clip_grad_norm: true
        clip_grad_val: 5
        collect_with_grad: false
        create_json: true
        evaluation: true
        evaluation_deterministic_actions: true
        evaluation_episodes: 10
        evaluation_interval: 120000
        evaluation_static: false
        exclude_buffer_from_checkpoint: false
        exploration_anneal_frames: null
        exploration_eps_end: 0.01
        exploration_eps_init: 0.8
        gamma: 0.99
        hard_target_update_frequency: 5
        keep_checkpoints_num: 3
        loggers:
            - csv
            - wandb
        lr: 5e-05
        max_n_frames: 600000
        max_n_iters: null
        off_policy_collected_frames_per_batch: 6000
        off_policy_init_random_frames: 0
        off_policy_memory_size: 1000000
        off_policy_n_envs_per_worker: 10
        off_policy_n_optimizer_steps: 1000
        off_policy_prb_alpha: 0.6
        off_policy_prb_beta: 0.4
        off_policy_train_batch_size: 128
        off_policy_use_prioritized_replay_buffer: false
        on_policy_collected_frames_per_batch: 6000
        on_policy_minibatch_size: 400
        on_policy_n_envs_per_worker: 10
        on_policy_n_minibatch_iters: 45
        parallel_collection: false
        polyak_tau: 0.005
        prefer_continuous_actions: true
        project_name: benchmarl
        render: true
        restore_file: null
        restore_map_location: null
        sampling_device: cpu
        save_folder: null
        share_policy_params: true
        soft_target_update: true
        train_device: cpu
model_config:
    value:
        _is_critic: false
        activation_class: torch.nn.modules.activation.Tanh
        activation_kwargs: null
        layer_class: torch.nn.modules.linear.Linear
        norm_class: null
        norm_kwargs: null
        num_cells:
            - 256
            - 256
        num_feature_dims: 1
model_name:
    value: mlp
on_policy:
    value: true
seed:
    value: 0
task_config:
    value:
        max_steps: 250
        n_agents: 4
        package_length: 0.6
        package_mass: 50
        package_width: 0.6
task_name:
    value: reverse_transport
